### ISSUE TITLE
Javafml version 44 needed found 43 

### ISSUE THREAD

**Issue by KawaiiiSheep** [Keksuccino/Auudio#1]
as the title says i need javaflm v 44 instead of 43 and im unable to find where to download the new version 
any help would be appreciated
full error code below:
Missing language javafml version [44,) wanted by auudio_forge_1.0.3_MC_1.19.3.jar, found 43

**Comment by Keksuccino** [comment]
You are trying to load a MC 1.19.3 mod in MC 1.19.2.
